# Generated by Django 3.2.5 on 2021-07-28 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cordinate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cordinates', models.TextField()),
                ('output', models.TextField()),
                ('distance', models.DecimalField(decimal_places=20, max_digits=22)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=60)),
                ('modified_by', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Cordinate',
                'verbose_name_plural': 'Cordinates',
                'db_table': 'Cordinate',
                'managed': True,
            },
        ),
    ]
